apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scores-app.fullname" . }}-init-sql
  labels:
    {{- include "scores-app.labels" . | nindent 4 }}
data:
  init.sql: |
    -- Your SQL initialization script goes here
