apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scores-app.fullname" . }}-app
  labels:
    {{- include "scores-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scores-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scores-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "scores-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: {{ .Values.config.mysqlHost | quote }}
            - name: MYSQL_USER
              value: {{ .Values.config.mysqlUser | quote }}
            - name: MYSQL_DB
              value: {{ .Values.config.mysqlDatabase | quote }}
            - name: MYSQL_PASSWORD
              value: ""  # No password
