apiVersion: v1
kind: Service
metadata:
  name: {{ include "scores-app.fullname" . }}-app
  labels:
    {{- include "scores-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: {{ include "scores-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
